// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    Footer2: typeof import('./components/Footer2.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    README: typeof import('./components/README.md')['default']
    Social: typeof import('./components/Social.vue')['default']
  }
}

export { }
